"""Establishments

Revision ID: 23253751f837
Revises: a0e2ff66ecc2
Create Date: 2023-05-13 11:54:22.374417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23253751f837'
down_revision = 'a0e2ff66ecc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coords', sa.VARCHAR(length=21), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('website', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_establishment',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'establishment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_establishment')
    op.drop_table('establishments')
    op.drop_table('categories')
    # ### end Alembic commands ###
